//* Initialize global variables to be used across functions
const baseUrl = "https://pokeapi.co/api/v2/";
const containerDiv = document.getElementById('container');
let pokeName = null;
let pokeNum = null;
let pokeDiv = null;
let pokeAbilityName = null;
let pokeAbility = "";
let pokeAbilityArray = [];
let numOfAbilities = "";

const searchDiv = document.getElementById('searchContainer');

//* Turns users search value into a string to be manipulated later 
function mkString(stringInput) {
    return stringInput.toString();
}
//* Changes string (user input value) to all lower case letters to match the name in the Poke API
function lowCaseSearch(string) {
    return string.toLowerCase();
}
//* Function triggered when user hits the search button on the HTML
const getPokeResults = () => {
    
    const searchInput = document.getElementById("search");
    //* Triggers function "mkString" and assigns "name" a value
    const name = mkString(searchInput.value);
    // console.log(name);

    //* There are two ways to pull up a pokemon 1. By searching for a specific pokemon (function getPokeResults()). 2. The other by randomly picking on by the pokemon ID number (function getRandomPokemon())
    //! pokeNum refers to the function getRandomPokemon and is used later to help display the proper pokemon abilities and not return an error. pokeNum is assigned value "null" so that the function (nameAbilities) is triggered and the proper fetch is used.
    pokeNum = null;
    
    
    pokeName = lowCaseSearch(name)
    // console.log("this button works")
    //* searchContainer is set to have no value here so that if the .catch is triggered then the text it displays will be wiped once another search has happened
    searchContainer.textContent = ""

    //* gets the information of the pokemon that was searched for by user
    fetch(`https://pokeapi.co/api/v2/pokemon/${pokeName}`)
        .then(res => res.json())
        .then(data => {
            // console.log(data.name);
            //* Triggers function (makePokeDiv) and gives the function information on what image to display, the name, and the div where it will be populated at in the HTML page.
            makePokeDiv(data.sprites.other["official-artwork"].front_default, data.name, searchDiv)

            for (i = 0; i < data.types.length; i++){
                console.log(data.types[i].type.name);
                
                // makePokeTypeDiv(data.types[i].type.name, searchDiv)
            }

        }).catch((err) => { //* If the API cannot locate the pokemon the user searched for it will add text to the HTML to let the user know that the information that was typed did not return any results. 
            console.log("Pokemon not found", err);
            searchContainer.textContent = "Sorry I can't find that pokemon!"
        });
    // e.preventDefault();
    //* clears what the user inputed into the search bar
    searchInput.value = ""
}
//* Function triggered when user clicks the Random pokemon button
const getRandomPokemon = () => {
    // console.log("this random button works")
    pokeNum = Math.floor(Math.random() * 905) + 1
    // console.log(pokeNum)

    //* There are two ways to pull up a pokemon 1. By searching for a specific pokemon (function getPokeResults()). 2. The other by randomly picking on by the pokemon ID number (function getRandomPokemon())
    //! pokeName refers to the function getPokeResults and is used later to help display the proper pokemon abilities and not return an error. pokeName is assigned value "null" so that the function (numAbilities) is triggered and the proper fetch is used.
    pokeName = null;

    //* searchContainer is set to have no value here so that if the .catch is triggered then the text it displays will be wiped once this button is pressed 
    searchContainer.textContent = ""

    // const pokeDiv = document.getElementById('pokeInfo')
    // const pokeAbility = document.getElementById('ability')
    //* Gets the pokemon with the random number that was generated by searching by the pokemon ID in the API
    fetch(`https://pokeapi.co/api/v2/pokemon/${pokeNum}`)
        .then(res => res.json())
        .then(data => {
            // console.log(data.name);
            //* Triggers function (makePokeDiv) and gives the function information on what image to display, the name, and the div where it will be populated at in the HTML page
            makePokeDiv(data.sprites.other["official-artwork"].front_default, data.name, searchDiv)
            

        }).catch((err) => {//! This function should not trigger an error but the catch is still here just in case
            console.log("Pokemon not found", err);
            searchContainer.textContent = "Sorry I can't find that pokemon!"
        });
    
    
    // e.preventDefault();
}

const makePokeDiv = (image, name, divForInfo) => {

    //* This if else statement will wipe the previously generated pokemon if there is information in the pokeDiv and generate new information if provided the proper input. 
    if (searchDiv.firstElementChild != null) {
        searchDiv.removeChild(pokeDiv)
    } else {null}
    
    //* Ternary that does the samething as the if else above. Commented it out for testing purposes.
    // searchDiv.firstElementChild != null
    // // if true
    // ? searchDiv.removeChild(pokeDiv)
    // // if false
    // : null
    

    
    // console.log("this function makePokeDiv works")
    //* Initializing and assigning  new variables with their values
    pokeDiv = document.createElement('div')
    
    const pokePic = document.createElement('img')
    const pokeName = document.createElement('h1')
    pokeAbility = document.createElement('button')
    

    //* Gives the created variables their information to display from the API
    pokePic.src = image
    pokeName.textContent = name.charAt(0).toUpperCase() + name.slice(1); //! capitalizes the first letter in pokemon name
    pokeAbility.setAttribute("id", "pokeAbilityBtn")//! assigns id to the new button
    pokeAbility.onClick = viewAbilities //! creates a function to be triggeres when button is clicked
    pokeDiv.setAttribute("id", "pokeInfo")

    //* adds all the elements to the created pokeDiv
    pokeDiv.appendChild(pokePic)
    pokeDiv.appendChild(pokeName)
    pokeAbility.innerHTML = 'Show Abilities';
    pokeAbility.onclick = viewAbilities;
    pokeDiv.appendChild(pokeAbility)


    divForInfo.appendChild(pokeDiv)
    
    
}
//* OnClick function for ability button
const viewAbilities = () => {
    
    // console.log(`pokeName = ${pokeName}`);
    // console.log(`pokeNum = ${pokeNum}`);
    // console.log("viewAbilities work")
    //* if else statement to lead the code to the proper fetch statement 
    //! i.e. if user searched by name function nameAbilities will be triggered. If user generated a number function numAbilities will be triggered
    if (pokeName === null) {
        numAbilities()

    } 
    else {
        nameAbilities()
}

}
const hideAbilities = () => {
    const abilities = document.getElementById('ability')
    console.log("hideAbilities work")    
    console.log(`numOfAbilities = ${numOfAbilities}`);
    for (i = 1; i <= numOfAbilities; i++){
        console.log(i);
        // if (i < numOfAbilities) {
        //     abilities.remove();            
        // } else {console.log('numOfAbilities loop is done');}
        switch (`${i}`) {
            case "1":
                abilities.remove();
                break;
            case "2":
                abilities.remove();
                break;
            case "3":
                abilities.remove();
                break;
            default:
                console.log('numOfAbilities loop is done');
        }
    }

}
//* function to display the abilities of pokemon that was randomly generated
const numAbilities = () => {
    console.log('Start of numAbilities function');
    //* clears array before abilities are genereated for a new pokemon
    pokeAbilityArray = [];

    fetch(`https://pokeapi.co/api/v2/pokemon/${pokeNum}`)
    .then(res => res.json())
    .then(data => {
        // console.log(data.abilities);
        numOfAbilities = data.abilities.length;        
        
        for (i = 0; i < numOfAbilities; i++){
            console.log(data.abilities[i].ability.name);

            pokeAbilityArray.push(data.abilities[i].ability.name);
            makePokeAbilityDiv(data.abilities[i].ability.name, pokeDiv)
        }

        console.log(pokeAbilityArray);
        
    }).catch((err) => {
        // searchContainer.textContent = "Sorry I can't do that!"
        console.log(err);
    });
}
//* function to display the abilities of pokemon that was searched by user
const nameAbilities = () => {
    console.log('Start of nameAbilities function');
    fetch(`https://pokeapi.co/api/v2/pokemon/${pokeName}`)
    .then(res => res.json())
    .then(data => {
        // console.log(data.abilities);
        numOfAbilities = data.abilities.length;

        for (i = 0; i < numOfAbilities; i++){
            console.log(data.abilities[i].ability.name);
            makePokeAbilityDiv(data.abilities[i].ability.name, pokeDiv)
        }
        
        
    }).catch((err) => {
        // searchContainer.textContent = "Sorry I can't do that!"
        console.log(err);
    });
}
const makePokeAbilityDiv = (abilityName, divForInfo) => {
    pokeAbilityName = document.createElement('p')
    pokeAbilityDiv = document.createElement('div')
    
    pokeAbilityName.textContent = abilityName.charAt(0).toUpperCase() + abilityName.slice(1);
    pokeAbilityDiv.setAttribute("id", "ability")
    pokeAbilityDiv.appendChild(pokeAbilityName)
    pokeAbility.innerHTML = 'Hide Abilities';
    pokeAbility.onclick = hideAbilities;

    divForInfo.appendChild(pokeAbilityDiv)
}
/*const makePokeTypeDiv = (abilityName, divForInfo) => {
    pokeAbilityName = document.createElement('div')
    
    pokeAbilityName.textContent = abilityName.charAt(0).toUpperCase() + abilityName.slice(1);
    pokeAbilityName.setAttribute("id", "ability")

    pokeDiv.appendChild(pokeAbilityName)

    divForInfo.appendChild(pokeDiv)

}*/